import streamlit as st
from binance.client import Client
import pandas as pd

# client = Client()
# tickers = ['BTCUSDT','XRPUSDT',
#  'TRXUSDT',
#  'WAVESUSDT',
#  'ZILUSDT',
#  'ONEUSDT',
#  'COTIUSDT',
#  'SOLUSDT',
#  'EGLDUSDT',
#  'AVAXUSDT',
#  'NEARUSDT',
#  'FILUSDT',
#  'AXSUSDT',
#  'ROSEUSDT',
#  'ARUSDT',
#  'MBOXUSDT',
#  'YGGUSDT',
#  'BETAUSDT',
#  'PEOPLEUSDT',
#  'EOSUSDT',
#  'ATOMUSDT',
#  'FTMUSDT',
#  'DUSKUSDT',
#  'IOTXUSDT',
#  'OGNUSDT',
#  'CHRUSDT',
#  'MANAUSDT',
#  'XEMUSDT',
#  'SKLUSDT',
#  'ICPUSDT',
#  'FLOWUSDT',
#  'WAXPUSDT',
#  'FIDAUSDT',
#  'ENSUSDT',
#  'SPELLUSDT',
#  'LTCUSDT',
#  'IOTAUSDT',
#  'LINKUSDT',
#  'XMRUSDT',
#  'DASHUSDT',
#  'MATICUSDT',
#  'ALGOUSDT',
#  'ANKRUSDT',
#  'COSUSDT',
#  'KEYUSDT',
#  'XTZUSDT',
#  'RENUSDT',
#  'RVNUSDT',
#  'HBARUSDT',
#  'BCHUSDT',
#  'COMPUSDT',
#  'ZENUSDT',
#  'SNXUSDT',
#  'SXPUSDT',
#  'SRMUSDT',
#  'SANDUSDT',
#  'SUSHIUSDT',
#  'YFIIUSDT',
#  'KSMUSDT',
#  'DIAUSDT',
#  'RUNEUSDT',
#  'AAVEUSDT',
#  '1INCHUSDT',
#  'ALICEUSDT',
#  'FARMUSDT',
#  'REQUSDT',
#  'GALAUSDT',
#  'POWRUSDT',
#  'OMGUSDT',
#  'DOGEUSDT',
#  'SCUSDT',
#  'XVSUSDT',
#  'ASRUSDT',
#  'CELOUSDT',
#  'RAREUSDT',
#  'ADXUSDT',
#  'CVXUSDT',
#  'WINUSDT',
#  'C98USDT',
#  'FLUXUSDT',
#  'ENJUSDT',
#  'FUNUSDT',
#  'KP3RUSDT',
#  'ALCXUSDT',
#  'ETCUSDT',
#  'THETAUSDT',
#  'CVCUSDT',
#  'STXUSDT',
#  'CRVUSDT',
#  'MDXUSDT',
#  'DYDXUSDT',
#  'OOKIUSDT',
#  'CELRUSDT',
#  'RSRUSDT',
#  'ATMUSDT',
#  'LINAUSDT',
#  'POLSUSDT',
#  'ATAUSDT',
#  'RNDRUSDT',
#  'NEOUSDT',
#  'ALPHAUSDT',
#  'XVGUSDT',
#  'KLAYUSDT',
#  'DFUSDT',
#  'VOXELUSDT',
#  'LSKUSDT',
#  'KNCUSDT',
#  'NMRUSDT',
#  'MOVRUSDT',
#  'PYRUSDT',
#  'ZECUSDT',
#  'CAKEUSDT',
#  'HIVEUSDT',
#  'UNIUSDT',
#  'SYSUSDT',
#  'BNXUSDT',
#  'GLMRUSDT',
#  'LOKAUSDT',
#  'CTSIUSDT',
#  'REEFUSDT',
#  'AGLDUSDT',
#  'MCUSDT',
#  'ICXUSDT',
#  'TLMUSDT',
#  'MASKUSDT',
#  'IMXUSDT',
#  'XLMUSDT',
#  'BELUSDT',
#  'HARDUSDT',
#  'NULSUSDT',
#  'TOMOUSDT',
#  'NKNUSDT',
#  'BTSUSDT',
#  'LTOUSDT',
#  'STORJUSDT',
#  'ERNUSDT',
#  'XECUSDT',
#  'ILVUSDT',
#  'JOEUSDT',
#  'SUNUSDT',
#  'ACHUSDT',
#  'TROYUSDT',
#  'YFIUSDT',
#  'CTKUSDT',
#  'BANDUSDT',
#  'RLCUSDT',
#  'TRUUSDT',
#  'MITHUSDT',
#  'AIONUSDT',
#  'ORNUSDT',
#  'WRXUSDT',
#  'WANUSDT',
#  'CHZUSDT',
#  'ARPAUSDT',
#  'LRCUSDT',
#  'IRISUSDT',
#  'UTKUSDT',
#  'QTUMUSDT',
#  'GTOUSDT',
#  'MTLUSDT',
#  'KAVAUSDT',
#  'DREPUSDT',
#  'OCEANUSDT',
#  'UMAUSDT',
#  'FLMUSDT',
#  'UNFIUSDT',
#  'BADGERUSDT',
#  'PONDUSDT',
#  'PERPUSDT',
#  'TKOUSDT',
#  'GTCUSDT',
#  'TVKUSDT',
#  'MINAUSDT',
#  'RAYUSDT',
#  'LAZIOUSDT',
#  'AMPUSDT',
#  'BICOUSDT',
#  'CTXCUSDT',
#  'FISUSDT',
#  'BTGUSDT',
#  'TRIBEUSDT',
#  'QIUSDT',
#  'PORTOUSDT',
#  'DATAUSDT',
#  'NBSUSDT',
#  'EPSUSDT',
#  'TFUELUSDT',
#  'BEAMUSDT',
#  'REPUSDT',
#  'PSGUSDT',
#  'WTCUSDT',
#  'FORTHUSDT',
#  'BONDUSDT',
#  'ZRXUSDT',
#  'FIROUSDT',
#  'SFPUSDT',
#  'VTHOUSDT',
#  'FIOUSDT',
#  'PERLUSDT',
#  'WINGUSDT',
#  'AKROUSDT',
#  'BAKEUSDT',
#  'ALPACAUSDT',
#  'FORUSDT',
#  'IDEXUSDT',
#  'PLAUSDT',
#  'VITEUSDT',
#  'DEGOUSDT',
#  'XNOUSDT',
#  'STMXUSDT',
#  'JUVUSDT',
#  'STRAXUSDT',
#  'CITYUSDT',
#  'JASMYUSDT',
#  'DEXEUSDT',
#  'OMUSDT',
#  'MKRUSDT',
#  'FXSUSDT',
#  'ETHUSDT',
#  'ADAUSDT',
# 'BNBUSDT',
# 'SHIBUSDT']

# dropdown = st.selectbox("Pick your coin", tickers)
# start = st.date_input('Start', value=pd.to_datetime('2022-01-01'))

# def getdata(symbol, start):
#     start = str(start)
#     frame = pd.DataFrame(client.get_historical_klines(symbol,
#                                                     '1d',
#                                                     start))
#     frame = frame.iloc[:, :2]
#     frame.columns = ['Time', 'Price' ]
#     frame.set_index('Time', inplace=True)
#     frame.index = pd.to_datetime(frame.index, unit='ms')
#     frame = frame.astype(float)
#     return frame

# df = getdata(dropdown, start)

# st.header(dropdown + " Price Chart")
# st.line_chart(df)
# st.dataframe(df)


st.markdown('''# **Crypto Price App powered by Binance API**
Simple UI displaying crypto prices using streamlit powered by Binance API.
''')

st.header('**Selected Price**')

# Load market data from Binance API
df = pd.read_json('https://api.binance.us/api/v3/ticker/24hr')

st.header('**All Prices**')
st.dataframe(df)